sonar.projectKey=lavender-notes
sonar.projectName=Lavender Notes App
sonar.projectVersion=1.0.0
sonar.organization=qazafi-hussain-developer
sonar.host.url=https://sonarcloud.io

sonar.sources=frontend/src,backend/src
sonar.exclusions=**/node_modules/**,**/*.test.js,**/*.test.jsx,**/coverage/**,**/dist/**,**/build/**

# Only backend tests (frontend tests don't have a separate folder)
sonar.tests=backend/tests
sonar.test.inclusions=**/*.test.js

sonar.javascript.file.suffixes=.js,.jsx
sonar.sourceEncoding=UTF-8